name: Pipeline teste

on: 
  push:
    branches:
        - dev

jobs:
  validar-push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code :
        uses: actions/checkout@v3

      - name: Checkout index :
        run: test -f index.html
